#!/usr/bin/env bash
# Install NGINX on my server

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
newlines="rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;"
sudo sed -i "/server_name _/a $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
