#!/usr/bin/env bash
# Displays a list of currently running processes that:
# Must show all processes, for all users, including those which might not have a TTY
# Display a user-oriented format
# Show process hierarchy
# PS_FORMAT='user,pid,%cpu,%mem,vsz,rss,tty,stat,start_time,bsdtime,args' ps -e --forest --sort=user

ps axuf
