#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" when receiving a SIGTERM signal
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal

sleep() {
  ! read -rt "$1"
} <> <(:)

echo "$$" >| "${pidfile:=/var/run/holbertonscript.pid}"

trap '
  echo "Y U no love me?!"
' INT
trap '
  rm -f "${pidfile}" 2>/dev/null
  exit 131
' QUIT
trap '
  echo "I hate the kill command"
  rm -f "${pidfile}" 2>/dev/null
  exit 143
' TERM
