#!/usr/bin/env bash
# Indefinitely writes "I am alive" to the file /tmp/my_process.

sleep() {
  ! read -rt "$1"
} <> <(:)

while true
do
  echo 'I am alive!'
  sleep 2
done > "${TMPDIR:-/tmp}/my_process"
