#!/usr/bin/env bash
#  displays the content of the file /etc/passwd
#+ only displays the:
#+ username
#+ group id
#+ Home directory path for the user


while IFS=':' read -r login _ uid _ _ home _
do
    printf '%s:%s:%s\n' "${login}" "${uid}" "${home}"
done </etc/passwd
