#!/usr/bin/env bash
# displays the content of the current directory:
#+ In a list format
#+ Where only the part of the name after the first dash is displayed

shopt -s nullglob

for file in *
do
    echo "${file#*-}"
done
