#!/usr/bin/env bash
# Block all incoming traffic not on one of port 22, 80, or 443

sudo apt update ; sudo apt install -y ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow 22/TCP ; sudo ufw allow 80/TCP ; sudo ufw allow 443/TCP
sudo ufw enable
