#!/usr/bin/env bash
# Run NGINX as nginx listening to all active IPs on port 8080
pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 0644 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
